bcgov/backup-container

docker/backup.sh
- Some systems do not like working with padded numbers.
- Remove the padding from dates used in calculations.
=> Fix bug in date calculations

README.md, config/backup.conf, docker/Dockerfile, docker/backup.sh
- Integrates go-crond to support cron tab based scheduling.
- Uses an enhanced version that supports log output from scheduled jobs.
- Auto detects cron settings and switches to Cron Mode when detected.
- Retains backward compatibility for the "Legacy" mode; now the fallback default.
=> Add cron scheduling support to the pod deployment.

docker/Dockerfile, docker/backup.sh
- fixes #33
- Start go-crond as a background task and wait on it.  This ensures the main script remains as PID 1 and can reap any adopted child processes.
- Ensure a proper shutdown.
=> Fix defunct PostgreSQL processes

README.md, openshift/templates/backup/backup-cronjob.yaml
This PR updates the default schedule in the cronjob to run at 1 AM (local time zone). The documentation was implying UTC time which is no longer the case. 
This is meant to bring the default to alignment with the backup.conf example.
Bug fix (non-breaking change which fixes an issue)
Documentation (non-breaking change with enhancements to documentation)
=> Change cronjob default schedule value

openshift/templates/backup/backup-cronjob.yaml
Small update to backup-cronjob.yaml to synchronize CronJob environment variable keys to ConfigMap keys for RETENTION.
Verified on Common Services Showcase Team GETOK and CHES projects.
=> Match Env Var Keys to ConfigMap Keys for RETENTION options.

docker/Dockerfile
Clean version of suggested https://github.com/BCDevOps/backup-container/pull/45
Resolves the following issue:
```
STEP 7: ARG GOCROND_VERSION=0.6.3
e55ddcc18af7ee9b5dea5822e3b9172f85bcee5eef6afb272e09d61d2013cdb8
STEP 8: ADD https://github.com/$SOURCE_REPO/go-crond/releases/download/$GOCROND_VERSION/go-crond-64-linux /usr/bin/go-crond
error: build error: error building at STEP "ADD https://github.com/$SOURCE_REPO/go-crond/releases/download/$GOCROND_VERSION/go-crond-64-linux /usr/bin/go-crond": source can't be a URL for COPY
```
Best practices may have changed, they currently suggest curl:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
I also had to move this operation, installing go-crond, after switching to ROOT so that curl had the permissions …
=> Update Docker file from ADD to RUN curl, build issue

openshift/templates/backup/backup-cronjob.yaml
- Change environment variables for username and password in cronjob template to match documentation, and what backup script expects.
=> Changed environment names to match documentation.

openshift/templates/backup/backup-cronjob.yaml
This PR parameterizes the image registry in the image spec. The parameter defaults to the OCP4 variant.
=> Parameterize image registry in cronjob

docker/backup.mongo.plugin
- Kill the mongo process when the `db.shutdownServer` fails to stop the server.
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
=> Update the onStopServer function for Mongo

README.md, docker/Dockerfile
This PR is very similar to https://github.com/BCDevOps/backup-container/pull/62/files
Upgrade to V13 because we use V13 for our project in OCP. 
I haven't tested with V12 however, having an upgrade to match version seems more reliable.
=> Upgrade base image to V13.

docker/Dockerfile, docker/Dockerfile_MSSQL, docker/Dockerfile_MariaDB, docker/Dockerfile_Mongo, docker/backup.logging, docker/backup.settings, docker/webhook-template.json
- Format messages before sending.
- Use curl's `--data-urlencode` flag to properly url encode message content.
- Remove the webhook template.
- Remove all manual message escaping.
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
=> Fix url encoding issue causing webhook message delivery to fail

README.md
The directory in the helm-charts repo appears to have been moved from:
https://github.com/bcgov/helm-charts/tree/master/backup-storage
to: 
https://github.com/bcgov/helm-charts/tree/master/charts/backup-storage
=> Fix broken helm-charts link

.gitignore, DEVELOPER.md, README.md, config/backup-dev.conf, docker-compose.yml, docker/Dockerfile, docker/backup.config.utils, docker/backup.s3, docker/backup.sh, docker/backup.utils
This PR adds the following features:
- Add support for S3 compatible object storage systems. It has been tested agains AWS S3 and Minio;
- A docker-compose stack for development purposes. The added DEVELOPER.md describes how to start the docker stack, populate a sample PostgreSQL database, and mount the `backup.config` sample file provided. It also configures `minio` as a S3 compatible storage system for testing;
- Updated documentation to include S3 parameters and a few other edits for clarity and simplicity.
=> feat: add s3 support and update documentation

docker/backup.config.utils, docker/backup.postgres.plugin, docker/backup.sh, docker/backup.usage
- resolves #56
- Adds the `-I` option as discussed to control the value of `ON_ERROR_STOP` in the postgres onRestoreDatabase implementation.
- An `ignoreErrors` function was added to allow other implementations and scripts to test for the "ignore errors" option.
=> Add support for ignoring SQL errors during postgres database restore.

docker/backup.postgres.plugin
While the change introduced in #115 achieves role backups, the switch from the gzip/gunzip tool to tar introduces file boundary artifacts in the backup stream, which psql is unable to handle. By rolling back to using gzip/gunzip in lieu of tar, we are able to concatenate and preserve equivalent behavior, but without the extraneous file boundary markers.
=> Revert postgres plugin to use gzip and gunzip

docker/backup.postgres.plugin
This drops the metric helpers and user management schemas used by patroni, allowing the backup container to verify and restore patroni stateful sets (using postgres 13 server specifically).  
Note the -I flag is still needed for these to work:
`/backup.sh -I -r  <databaseSpec/>`
and 
`./backup.sh -I -v all`
To validate the db.
=> fix: allow backup verification and restore to work with patroni

openshift/templates/backup/backup-deploy.yaml
Dropped `DeploymentConfig` adding `Deployment`.
`DeploymentConfig` is now deprecated.
- **Replace deprecated DeploymentConfigs with deployments:** [RedHat Learning Developers Docs](https://developers.redhat.com/learning/learn:openshift:replace-deprecated-deploymentconfigs-deployments/resource/resources:convert-deploymentconfig-deployment)
- Co-Authored by: @DerekRoberts
=> feat: replace deprecated deploymentconfig by deployment

config/backup.conf, docker/backup.config.utils, docker/backup.postgres.plugin
Added the ability to specify a custom schema name for backup verification in postgres when using the configuration file spec.
Following the convention used for JDBC, the schema can be specified by adding `?verifySchema=my_schema` to the database spec.
This was developed as a set of postgres-specific overrides since other supported database providers do not have the concept of schema and it was simpler to customize one instance of the function to grab the database name from the connection spec rather than handling the different scenarios in the same function, but it can be refactored if necessary.
One thing this pattern could also be used for in the future is to specify the auth database for `mongodb` in the spec rather than using an environment variable like it is currently set-up to do. …
=> Add ability to specify custom schema for verification in postgres

docker/backup.config.utils
A previous change broke hostname parsing when using the format `databasetype=hostname/port`. This updated expression should resolve that, and work in both scenarios (with/without database prefix).
=> Fix hostname sed expression

docker/Dockerfile, docs/TipsAndTricks.md
Update the Dockerfile image to add postgresql 16 support.
I have deployed and tested this in our openshift dev instance running against a postgresql 16 instance and both the manual and cron backup processes ran successfully. Some additional testing against older postgres instances would be great.
=> Upgrade to postgres 16

.github/workflows/publish.yaml
- Default to `linux/amd64`, not all base image support `linux/arm64`.
- Make sure the workflow is using the related version of `./.github/actions/publish-image`, then have the build checkout the desired git ref.
=> Update publish workflow

docker/backup.postgres.plugin
- Fix the issue where the Postgres backup could fail silently, creating a corrupt backup.
- The backup is comprised of a number of steps.
- The return codes for each of the steps was not being checked for success and an erroneous success code could be returned by the process.
Scenario:
- The backup could fail at any point due to running out of disk space.
- The resulting archive would contain an incomplete (corrupt) backup.
- If backup verification was NOT enabled, the issue would go completely undetected (i.e. no error notifications, only success notifications).
Backup Corruption Detection:
- Enable backup verification.
- In the above scenario the corrupt backup would fail validation, alerting users of the issue; how the issue was discovered.
=> Fix - Postgres backup could fail silently, producing a corrupt archive.
